packages:
  - '.wrwork/_wr-auth-admin-temp-prj'
  - '.wrwork/WaveEventManagement'
  - '.wrnode/locals/linked/@wrtools/internals-patcher/1.0.0'
  - '.wrnode/locals/linked/@webratio-tool/style-webdefault/9.3.2'
  - '.wrnode/locals/linked/@webratio-tool/style-common/9.3.2'
  - '.wrnode/locals/linked/@webratio-tool/js-bundler/9.3.2'
  - '.wrnode/locals/linked/@webratio-tool/htmlserver-loaders/9.3.2'
  - '.wrnode/locals/linked/@webratio-tool/htmlserver/9.3.2'
  - '.wrnode/locals/linked/@webratio-tool/htmleditor/9.3.2'
  - '.wrnode/locals/linked/@webratio-tool/html-library-def/9.3.2'
  - '.wrnode/locals/linked/@webratio-tool/client-htmllibrary/9.3.2'
  - '.wrnode/locals/linked/@webratio-tool/appbuilder/9.3.2'
  - '.wrnode/locals/linked/@webratio/xdata-websql/2.1.1'
  - '.wrnode/locals/linked/@webratio/xdata-rest/2.1.1'
  - '.wrnode/locals/linked/@webratio/xdata/2.1.1'
  - '.wrnode/locals/linked/@webratio/runtime/9.3.2'
  - '.wrnode/locals/linked/@webratio/mvc-web/9.3.2'
  - '.wrnode/locals/linked/@webratio/mvc/9.3.2'
  - '.wrnode/locals/linked/@webratio/logger/1.12.0'
  - '.wrnode/locals/linked/@webratio/components-client-validation/9.3.2'
  - '.wrnode/locals/linked/@webratio/components-client-operation/9.3.2'
  - '.wrnode/locals/linked/@webratio/components-client-content/9.3.2'
  - '.wrnode/locals/linked/@webratio/components-client-authentication/9.3.2'
  - '.wrnode/locals/linked/@webratio/commons/2.12.1'
  - '.wrnode/locals/linked/@types/wr-builder/9.3.2'
  - '!.wrnode'
  - '!.wrnode/virtual/*/linked'
  - '!**/NativePlugins/**'
