-- Nuove tabelle aggiunte al modello Weave
-- Eseguire questo script dopo il deploy per aggiungere le tabelle mancanti

-- Aggiunta colonne mancanti alla tabella USER_3 (se non esistono)
-- (ABBONAMENTO_ATTIVO rimosso dal modello, non necessario)

-- Aggiunta colonne mancanti a PRENOTAZIONE
ALTER TABLE "APP"."PRENOTAZIONE" ADD COLUMN "STATO_PAGAMENTO" VARCHAR(255);
ALTER TABLE "APP"."PRENOTAZIONE" ADD COLUMN "DOCUMENTO_VERIFICATO" SMALLINT;

-- Aggiunta colonne mancanti a EVENTO
ALTER TABLE "APP"."EVENTO" ADD COLUMN "CODICE_ACCESSO" VARCHAR(255);
ALTER TABLE "APP"."EVENTO" ADD COLUMN "DEADLINE_PRENOTAZIONE" TIMESTAMP;
ALTER TABLE "APP"."EVENTO" ADD COLUMN "PRENOTAZIONI_CHIUSE" SMALLINT;

-- Creazione tabella PAGAMENTO (cls6)
CREATE TABLE "APP"."PAGAMENTO" (
   "CODICE_PAGAMENTO" INTEGER NOT NULL,
   "IMPORTO" DECIMAL(19,2),
   "DATA_PAGAMENTO" TIMESTAMP,
   "STATO" VARCHAR(255),
   "TRANSAZIONE_ID_ESTERNO" VARCHAR(255),
   "PRENOTAZIONE_CODICE_PRENOTAZIONE" INTEGER,
   PRIMARY KEY ("CODICE_PAGAMENTO")
);

ALTER TABLE "APP"."PAGAMENTO" ADD CONSTRAINT FK_PAGAMENTO_PRENOTAZIONE
  FOREIGN KEY ("PRENOTAZIONE_CODICE_PRENOTAZIONE")
  REFERENCES "APP"."PRENOTAZIONE" ("CODICE_PRENOTAZIONE");

-- Creazione tabella WALLET_TRANSAZIONE (cls7)
CREATE TABLE "APP"."WALLET_TRANSAZIONE" (
   "CODICE_TRANSAZIONE" INTEGER NOT NULL,
   "IMPORTO" DECIMAL(19,2),
   "TIPO" VARCHAR(255),
   "DATA" TIMESTAMP,
   "USER_CODICE_UTENTE" INTEGER,
   PRIMARY KEY ("CODICE_TRANSAZIONE")
);

ALTER TABLE "APP"."WALLET_TRANSAZIONE" ADD CONSTRAINT FK_WALLET_USER
  FOREIGN KEY ("USER_CODICE_UTENTE")
  REFERENCES "APP"."USER_3" ("CODICE_USER");
