#Registered plugins
#Tue Jun 30 20:57:34 CEST 2026
components.0=C\:\\WebRatio\\WebRatio Platform Community 9.3.2\\WebRatio\\plugins\\com.webratio.components.web.controlflow_9.3.2.202604291841
components.1=C\:\\WebRatio\\WebRatio Platform Community 9.3.2\\WebRatio\\plugins\\com.webratio.components.web.operation_9.3.2.202604291841
components.2=C\:\\WebRatio\\WebRatio Platform Community 9.3.2\\WebRatio\\plugins\\com.webratio.components.web.session_9.3.2.202604291841
components.3=C\:\\WebRatio\\WebRatio Platform Community 9.3.2\\WebRatio\\plugins\\com.webratio.components.web.utility_9.3.2.202604291841
components.4=C\:\\WebRatio\\WebRatio Platform Community 9.3.2\\WebRatio\\plugins\\com.webratio.components.web.validation_9.3.2.202604291841
components.5=C\:\\WebRatio\\WebRatio Platform Community 9.3.2\\WebRatio\\plugins\\com.webratio.components.web.ws_9.3.2.202604291841
